-
  name:  'Nextcloud Asset Source Thumbnail'
  uriPattern: 'assetsource/nextcloud/{assetSourceIdentifier}/{fileId}/{width}/{height}'
  defaults:
    '@package':    'DL.AssetSource.Nextcloud'
    '@controller': 'Thumbnail'
    '@action':     'thumbnail'
  httpMethods: ['GET']
