Neos:
  Media:
    assetSources:
      nextcloud:
        assetSource: 'DL\AssetSource\NextCloud\AssetSource\NextCloudAssetSource'
        assetSourceOptions:
          label: Nextcloud

          # How many files are requested at maximum
          assetResultLimit: 200
          basePath: '/'

          server:
            baseUri: 'https://owncloud.lienert.cc'
            userName: ''
            password: ''

          previewableMimeTypes:
            - 'image/png'
            - 'image/jpeg'
            - 'image/gif'
            - 'image/x-xbitmap'
            - 'image/bmp'
            - 'image/tiff'
            - 'image/x-dcraw'
            - 'image/heic'
            - 'image/heif'
            - 'application/x-photoshop'
            - 'application/illustrator'
            - 'application/postscript'


  Flow:
    mvc:
      routes:
        DL.AssetSource.NextCloud:
          position: 'before Neos.Neos'
